spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
    prefix: classpath:/templates/    # 設定去這個資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5